# Generated by Django 3.2.5 on 2021-07-24 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeds', models.TextField()),
                ('num_of_cats', models.IntegerField()),
                ('looking_for', models.TextField()),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='main_app.collector')),
            ],
        ),
    ]
